### ISSUE TITLE
datajs 1.1.3

### ISSUE THREAD

**Issue by JohannesHoppe** [chiefy/datajs#3]
Version 1.1.3 can't be found on Codeplex, but here:
https://www.nuget.org/packages/datajs

Direct download:
https://api.nuget.org/packages/datajs.1.1.3.nupkg -> its a zip file!

Please also care about #2. Version numbers in file names break you code after `bower update`!

**Comment by JohannesHoppe** [comment]
Please don't forget to add the tag `v1.1.3` to your repo!

**Comment by chiefy** [comment]
:+1: done.
